#!/bin/bash

# Setup Email Notifications for Coach Core AI
# This script helps configure email notifications for waitlist signups

echo "🔧 Setting up email notifications for Coach Core AI..."

# Check if Firebase CLI is installed
if ! command -v firebase &> /dev/null; then
    echo "❌ Firebase CLI not found. Please install it first:"
    echo "npm install -g firebase-tools"
    exit 1
fi

echo "📧 Email Configuration Setup"
echo "================================"
echo ""
echo "To enable email notifications, you need to:"
echo ""
echo "1. Create a Gmail App Password:"
echo "   - Go to https://myaccount.google.com/security"
echo "   - Enable 2-Factor Authentication"
echo "   - Generate an App Password for 'Mail'"
echo ""
echo "2. Create or update the functions/.env file with your credentials"
echo ""

# Get email configuration
read -p "Enter your Gmail address: " GMAIL_USER
read -p "Enter your Gmail App Password: " GMAIL_PASSWORD
read -p "Enter notification email (where you want to receive signup alerts): " NOTIFICATION_EMAIL

ENV_FILE="functions/.env"

echo ""
echo "📝 Writing environment variables to $ENV_FILE"
cat > "$ENV_FILE" <<EOF
# Automatically generated by setup-email-notifications.sh
# Gmail credentials for waitlist notifications
GMAIL_USER=$GMAIL_USER
GMAIL_PASSWORD=$GMAIL_PASSWORD
NOTIFICATION_EMAIL=$NOTIFICATION_EMAIL
EOF

echo ""
echo "✅ Environment file updated!"
echo ""
echo "📋 Next steps:"
echo "1. Deploy the functions with the new environment variables:"
echo "   firebase deploy --only functions"
echo "2. Test the waitlist form at https://coach-core-ai.web.app/waitlist"
echo "3. Check your email for notifications!"
echo ""
echo "🔍 To view current config: firebase functions:config:get"
echo "📊 To view waitlist stats: firebase functions:shell (then call getWaitlistStats())"
