// Offensive Engine Data — Moderate Dataset
// Sourced from 67+ coaching references

import { OffensiveEngineData } from './schema';

export const offensiveEngineData: OffensiveEngineData = {
  routes: [
    // === EXISTING ROUTES (DO NOT MODIFY) ===
    {
      route_id: 'slant_5',
      route_number: 2,
      route_name: 'Slant',
      depth_yards: 5,
      break_direction: 'inside',
      stem: 'two_step_vertical',
      timing_second: 1.5,
      release_type: 'inside_release',
      key_coaching_points: ['push_vertical_2_steps', '45_degree_inside_cut', 'eyes_to_qb_at_break', 'catch_and_tuck'],
      effective_vs_coverage: ['cover_2', 'off_man', 'zone'],
      weak_vs_coverage: ['press_man', 'inside_shade'],
      tags: ['quick', 'short', 'man_beater', 'wr_route'],
    },
    {
      route_id: 'hitch_5',
      route_number: 0,
      route_name: 'Hitch',
      depth_yards: 5,
      break_direction: 'stop',
      stem: 'vertical_3_steps',
      timing_second: 1.3,
      release_type: 'outside_release',
      key_coaching_points: ['push_vertical_5_yards', 'stop_and_pivot_outside', 'snap_break_back_to_qb', 'sit_vs_zone'],
      effective_vs_coverage: ['off_man', 'zone', 'cover_3'],
      weak_vs_coverage: ['press_man', 'cover_2'],
      tags: ['quick', 'short', 'zone_beater', 'wr_route'],
    },
    {
      route_id: 'go_9',
      route_number: 9,
      route_name: 'Go',
      depth_yards: 20,
      break_direction: 'vertical',
      stem: 'vertical_release',
      timing_second: 3.5,
      release_type: 'vertical_release',
      key_coaching_points: ['attack_leverage', 'top_speed_by_10_yards', 'track_over_outside_shoulder', 'dont_look_too_early'],
      effective_vs_coverage: ['man', 'cover_1', 'single_high'],
      weak_vs_coverage: ['cover_2', 'cover_4', 'two_high'],
      tags: ['deep', 'man_beater', 'wr_route'],
    },
    {
      route_id: 'corner_10',
      route_number: 7,
      route_name: 'Corner',
      depth_yards: 10,
      break_direction: 'outside',
      stem: 'vertical_5_steps',
      timing_second: 2.2,
      release_type: 'outside_release',
      key_coaching_points: ['sell_vertical_stem', 'break_at_45_outside', 'landmark_back_pylon', 'stay_inbounds'],
      effective_vs_coverage: ['cover_3', 'man', 'cover_1'],
      weak_vs_coverage: ['cover_2', 'cover_4'],
      tags: ['intermediate', 'zone_beater', 'wr_route'],
    },
    {
      route_id: 'shallow_cross_5',
      route_number: 1,
      route_name: 'Shallow Cross',
      depth_yards: 3,
      break_direction: 'inside',
      stem: 'lateral_release',
      timing_second: 1.8,
      release_type: 'inside_release',
      key_coaching_points: ['stay_at_3_yards', 'run_full_speed_through_traffic', 'dont_drift_upfield', 'find_void_vs_zone'],
      effective_vs_coverage: ['man', 'cover_1', 'zone'],
      weak_vs_coverage: ['pattern_match', 'cover_4'],
      tags: ['quick', 'short', 'man_beater', 'wr_route', 'te_route'],
    },

    // === ROUTE TREE COMPLETION (#0-9) ===
    {
      route_id: 'bubble_screen_0',
      route_number: 0,
      route_name: 'Bubble Screen',
      depth_yards: 1,
      break_direction: 'outside',
      stem: 'lateral_release',
      timing_second: 0.8,
      release_type: 'immediate_lateral',
      key_coaching_points: ['eyes_to_qb_immediately', 'get_width_before_depth', 'catch_and_turn_upfield', 'read_blockers'],
      effective_vs_coverage: ['off_man', 'soft_zone', 'cover_3', 'cover_4'],
      weak_vs_coverage: ['press_man', 'cover_2'],
      tags: ['quick', 'screen', 'wr_route', 'rb_route'],
    },
    {
      route_id: 'flat_arrow_3',
      route_number: 1,
      route_name: 'Flat',
      depth_yards: 3,
      break_direction: 'outside',
      stem: 'lateral_release_to_flat',
      timing_second: 1.0,
      release_type: 'immediate_outside',
      key_coaching_points: ['no_drift_upfield', 'aim_bottom_of_numbers', 'quick_break_to_sideline', 'head_up_for_ball'],
      effective_vs_coverage: ['zone', 'cover_3', 'cover_4', 'soft_zone'],
      weak_vs_coverage: ['man', 'press_man'],
      tags: ['quick', 'short', 'zone_beater', 'rb_route', 'te_route'],
    },
    {
      route_id: 'comeback_14',
      route_number: 3,
      route_name: 'Comeback',
      depth_yards: 14,
      break_direction: 'outside',
      stem: 'vertical_7_steps',
      timing_second: 2.6,
      release_type: 'outside_release',
      key_coaching_points: ['sell_vertical_stem', 'snap_break_downhill', 'work_back_to_ball', 'toes_to_sideline', 'no_drifting'],
      effective_vs_coverage: ['off_man', 'cover_3', 'cover_1'],
      weak_vs_coverage: ['press_man', 'cover_2'],
      tags: ['intermediate', 'zone_beater', 'wr_route'],
    },
    {
      route_id: 'curl_12',
      route_number: 4,
      route_name: 'Curl',
      depth_yards: 12,
      break_direction: 'stop',
      stem: 'vertical_5_steps',
      timing_second: 2.2,
      release_type: 'vertical_stem',
      key_coaching_points: ['push_to_12_yards', 'snap_down_come_back', 'throttle_between_lbs', 'work_away_from_zone_eyes', 'sit_in_window'],
      effective_vs_coverage: ['zone', 'cover_3', 'cover_4', 'soft_zone'],
      weak_vs_coverage: ['man', 'press_man'],
      tags: ['intermediate', 'zone_beater', 'wr_route', 'te_route'],
    },
    {
      route_id: 'out_8',
      route_number: 5,
      route_name: 'Out',
      depth_yards: 8,
      break_direction: 'outside',
      stem: 'vertical_5_steps',
      timing_second: 1.8,
      release_type: 'vertical_stem',
      key_coaching_points: ['vertical_stem_no_drift', 'sharp_90_break', 'landmark_top_of_numbers', 'dont_round_the_route', 'burst_out_of_break'],
      effective_vs_coverage: ['cover_3', 'cover_1', 'zone'],
      weak_vs_coverage: ['cover_2', 'press_man'],
      tags: ['intermediate', 'zone_beater', 'wr_route'],
    },
    {
      route_id: 'dig_12',
      route_number: 6,
      route_name: 'Dig',
      depth_yards: 12,
      break_direction: 'inside',
      stem: 'vertical_5_steps',
      timing_second: 2.3,
      release_type: 'vertical_stem',
      key_coaching_points: ['push_vertical_to_safety_level', 'crisp_90_inside_cut', 'keep_shoulders_downfield', 'flatten_vs_man_sit_vs_zone', 'find_window_between_lbs'],
      effective_vs_coverage: ['cover_3', 'cover_1', 'man', 'cover_4'],
      weak_vs_coverage: ['tampa_2', 'cover_2'],
      tags: ['intermediate', 'both', 'wr_route', 'te_route'],
    },
    {
      route_id: 'post_12',
      route_number: 8,
      route_name: 'Post',
      depth_yards: 12,
      break_direction: 'inside',
      stem: 'vertical_5_steps',
      timing_second: 2.5,
      release_type: 'vertical_stem',
      key_coaching_points: ['stem_vertical_past_lbs', 'break_inside_at_12', 'attack_middle_of_field', 'split_safeties', 'adjust_angle_to_coverage_depth'],
      effective_vs_coverage: ['cover_3', 'cover_1', 'cover_4', 'man'],
      weak_vs_coverage: ['cover_2', 'tampa_2'],
      tags: ['deep', 'man_beater', 'wr_route'],
    },

    // === SPECIALTY ROUTES ===
    {
      route_id: 'wheel_vertical',
      route_number: -1,
      route_name: 'Wheel',
      depth_yards: 20,
      break_direction: 'vertical',
      stem: 'flat_release_then_vertical',
      timing_second: 3.0,
      release_type: 'flat_to_vertical',
      key_coaching_points: ['release_to_flat_first', 'turn_upfield_at_numbers', 'accelerate_vertically', 'stack_on_top_of_defender', 'track_ball_over_outside_shoulder'],
      effective_vs_coverage: ['man', 'cover_3', 'cover_1', 'zone'],
      weak_vs_coverage: ['cover_2', 'cover_4'],
      tags: ['deep', 'man_beater', 'rb_route', 'te_route'],
    },
    {
      route_id: 'seam_vertical',
      route_number: -1,
      route_name: 'Seam',
      depth_yards: 18,
      break_direction: 'vertical',
      stem: 'vertical_release_inside',
      timing_second: 2.8,
      release_type: 'inside_vertical',
      key_coaching_points: ['push_vertical_between_hash_and_numbers', 'bend_vs_2_high', 'stay_on_seam_vs_1_high', 'read_safety_leverage', 'throttle_in_hole_vs_zone'],
      effective_vs_coverage: ['cover_3', 'cover_1', 'man'],
      weak_vs_coverage: ['cover_2', 'tampa_2', 'cover_4'],
      tags: ['deep', 'both', 'te_route', 'wr_route'],
    },
    {
      route_id: 'drag_2',
      route_number: -1,
      route_name: 'Drag',
      depth_yards: 2,
      break_direction: 'inside',
      stem: 'lateral_release_inside',
      timing_second: 1.2,
      release_type: 'inside_release',
      key_coaching_points: ['stay_shallow_at_2_yards', 'run_through_traffic', 'dont_drift_upfield', 'find_void_vs_zone', 'keep_running_vs_man'],
      effective_vs_coverage: ['man', 'cover_1', 'zone'],
      weak_vs_coverage: ['pattern_match'],
      tags: ['quick', 'short', 'man_beater', 'wr_route', 'te_route'],
    },
    {
      route_id: 'stick_6',
      route_number: -1,
      route_name: 'Stick',
      depth_yards: 6,
      break_direction: 'stop',
      stem: 'vertical_3_steps',
      timing_second: 1.3,
      release_type: 'vertical_stem',
      key_coaching_points: ['push_vertical_to_6', 'stop_with_inside_step', 'sit_in_zone_window', 'work_away_from_lb', 'be_ready_for_quick_throw'],
      effective_vs_coverage: ['zone', 'cover_3', 'cover_4', 'soft_zone'],
      weak_vs_coverage: ['man', 'press_man'],
      tags: ['quick', 'short', 'zone_beater', 'te_route', 'wr_route'],
    },
    {
      route_id: 'whip_5',
      route_number: -1,
      route_name: 'Whip',
      depth_yards: 5,
      break_direction: 'outside',
      stem: 'inside_jab_then_outside',
      timing_second: 1.5,
      release_type: 'inside_fake_outside_break',
      key_coaching_points: ['jab_step_inside_first', 'snap_back_outside', 'create_separation_with_change_of_direction', 'settle_vs_zone'],
      effective_vs_coverage: ['man', 'press_man', 'cover_1'],
      weak_vs_coverage: ['zone', 'cover_3'],
      tags: ['quick', 'short', 'man_beater', 'wr_route', 'te_route'],
    },
    {
      route_id: 'sail_16',
      route_number: -1,
      route_name: 'Sail',
      depth_yards: 16,
      break_direction: 'outside',
      stem: 'vertical_7_steps',
      timing_second: 2.8,
      release_type: 'vertical_stem',
      key_coaching_points: ['push_vertical_deep', 'break_to_sideline_at_16', 'sit_behind_corner_in_cover_3', 'work_back_to_ball', 'landmark_sideline_at_depth'],
      effective_vs_coverage: ['cover_3', 'cover_1', 'zone'],
      weak_vs_coverage: ['cover_2', 'cover_4'],
      tags: ['deep', 'zone_beater', 'wr_route'],
    },
  ],

  formations: [
    // === EXISTING FORMATIONS (DO NOT MODIFY) ===
    {
      formation_id: 'shotgun_11_base',
      formation_name: 'Shotgun 11 Personnel',
      personnel: '11',
      alignment: {
        left_side: ['X'],
        right_side: ['Z', 'Y'],
        backfield: ['RB'],
      },
      spacing: {
        wr_splits: [12, 10, 2],
        ol_splits: [1.2, 1.2, 1.2, 1.2],
        rb_depth: 5.5,
      },
      strength: 'right',
      coverage_stress_points: ['slot_seam', 'boundary_wr'],
    },
    {
      formation_id: 'trips_right_base',
      formation_name: 'Trips Right',
      personnel: '11',
      alignment: {
        left_side: ['X'],
        right_side: ['H', 'Y', 'Z'],
        backfield: ['RB'],
      },
      spacing: {
        wr_splits: [12, 4, 7, 12],
        ol_splits: [1.2, 1.2, 1.2, 1.2],
        rb_depth: 5.5,
      },
      strength: 'right',
      coverage_stress_points: ['trips_overload', 'boundary_isolation'],
    },
    {
      formation_id: 'empty_10_base',
      formation_name: 'Empty 10 Personnel',
      personnel: '10',
      alignment: {
        left_side: ['X', 'H'],
        right_side: ['Z', 'Y', 'W'],
        backfield: [],
      },
      spacing: {
        wr_splits: [12, 6, 6, 8, 12],
        ol_splits: [1.5, 1.5, 1.5, 1.5],
        rb_depth: 0,
      },
      strength: 'right',
      coverage_stress_points: ['five_eligible', 'maximum_horizontal_stretch'],
    },

    // === PRO STYLE / UNDER CENTER ===
    {
      formation_id: 'pro_set_21_engine',
      formation_name: 'Pro Set',
      personnel: '21',
      alignment: {
        left_side: ['X'],
        right_side: ['Z', 'Y'],
        backfield: ['FB', 'RB'],
      },
      spacing: {
        wr_splits: [12, 10, 2],
        ol_splits: [1.2, 1.2, 1.2, 1.2],
        rb_depth: 7,
      },
      strength: 'right',
      coverage_stress_points: ['play_action_threat', 'run_pass_balance', 'te_mismatch'],
    },
    {
      formation_id: 'i_form_21_engine',
      formation_name: 'I-Formation',
      personnel: '21',
      alignment: {
        left_side: ['X'],
        right_side: ['Z', 'Y'],
        backfield: ['FB', 'RB'],
      },
      spacing: {
        wr_splits: [12, 10, 2],
        ol_splits: [1.2, 1.2, 1.2, 1.2],
        rb_depth: 7,
      },
      strength: 'right',
      coverage_stress_points: ['downhill_run_threat', 'play_action_depth', 'power_gap_scheme'],
    },
    {
      formation_id: 'ace_11_under_engine',
      formation_name: 'Ace (Under Center)',
      personnel: '11',
      alignment: {
        left_side: ['X', 'H'],
        right_side: ['Z', 'Y'],
        backfield: ['RB'],
      },
      spacing: {
        wr_splits: [12, 5, 10, 2],
        ol_splits: [1.2, 1.2, 1.2, 1.2],
        rb_depth: 6,
      },
      strength: 'right',
      coverage_stress_points: ['balanced_run_pass', 'te_seam_threat', 'play_action'],
    },

    // === SHOTGUN / SPREAD ===
    {
      formation_id: 'trips_right_11_engine',
      formation_name: 'Trips Right (Engine)',
      personnel: '11',
      alignment: {
        left_side: ['X'],
        right_side: ['H', 'Y', 'Z'],
        backfield: ['RB'],
      },
      spacing: {
        wr_splits: [12, 5, 7, 12],
        ol_splits: [1.2, 1.2, 1.2, 1.2],
        rb_depth: 5.5,
      },
      strength: 'right',
      coverage_stress_points: ['trips_overload', 'boundary_isolation'],
    },
    {
      formation_id: 'bunch_right_11_engine',
      formation_name: 'Bunch Right',
      personnel: '11',
      alignment: {
        left_side: ['X'],
        right_side: ['H', 'Y', 'Z'],
        backfield: ['RB'],
      },
      spacing: {
        wr_splits: [12, 5, 6, 7],
        ol_splits: [1.2, 1.2, 1.2, 1.2],
        rb_depth: 5.5,
      },
      strength: 'right',
      coverage_stress_points: ['natural_rub_picks', 'compressed_coverage_conflict', 'man_beater_alignment'],
    },
    {
      formation_id: 'quads_right_10_engine',
      formation_name: 'Quads Right',
      personnel: '10',
      alignment: {
        left_side: ['X'],
        right_side: ['H', 'Y', 'Z', 'W'],
        backfield: [],
      },
      spacing: {
        wr_splits: [12, 4, 6, 8, 12],
        ol_splits: [1.2, 1.2, 1.2, 1.2],
        rb_depth: 0,
      },
      strength: 'right',
      coverage_stress_points: ['extreme_numbers_advantage', 'force_five_defenders_to_quads', 'quick_game_overload'],
    },
    {
      formation_id: 'spread_2x2_10_engine',
      formation_name: 'Spread 2x2',
      personnel: '10',
      alignment: {
        left_side: ['X', 'H'],
        right_side: ['Y', 'Z'],
        backfield: [],
      },
      spacing: {
        wr_splits: [12, 6, 6, 12],
        ol_splits: [1.5, 1.5, 1.5, 1.5],
        rb_depth: 0,
      },
      strength: 'balanced',
      coverage_stress_points: ['maximum_horizontal_stress', 'five_eligible_quick_game', 'isolated_matchups'],
    },

    // === HEAVY / GOAL LINE ===
    {
      formation_id: 'jumbo_23_engine',
      formation_name: 'Jumbo Goal Line',
      personnel: '23',
      alignment: {
        left_side: ['Y1'],
        right_side: ['Y2', 'Y3'],
        backfield: ['FB', 'RB'],
      },
      spacing: {
        wr_splits: [2, 2, 2],
        ol_splits: [1.0, 1.0, 1.0, 1.0],
        rb_depth: 6,
      },
      strength: 'right',
      coverage_stress_points: ['8_man_front', 'power_at_point_of_attack', 'short_yardage'],
    },
    {
      formation_id: 'strong_i_22_engine',
      formation_name: 'Strong I',
      personnel: '22',
      alignment: {
        left_side: ['X'],
        right_side: ['Y1', 'Y2'],
        backfield: ['FB', 'RB'],
      },
      spacing: {
        wr_splits: [12, 2, 2],
        ol_splits: [1.0, 1.0, 1.0, 1.0],
        rb_depth: 7,
      },
      strength: 'right',
      coverage_stress_points: ['max_run_strength', 'isolated_x_backside', 'play_action_off_heavy'],
    },
    {
      formation_id: 'double_te_12_engine',
      formation_name: 'Double TE Split',
      personnel: '12',
      alignment: {
        left_side: ['X', 'Y1'],
        right_side: ['Z', 'Y2'],
        backfield: ['RB'],
      },
      spacing: {
        wr_splits: [12, 2, 10, 2],
        ol_splits: [1.2, 1.2, 1.2, 1.2],
        rb_depth: 5.5,
      },
      strength: 'balanced',
      coverage_stress_points: ['run_either_direction', 'balanced_te_threat', 'no_strength_tell'],
    },

    // === PISTOL / HYBRID ===
    {
      formation_id: 'pistol_trips_11_engine',
      formation_name: 'Pistol Trips',
      personnel: '11',
      alignment: {
        left_side: ['X'],
        right_side: ['H', 'Y', 'Z'],
        backfield: ['RB'],
      },
      spacing: {
        wr_splits: [12, 5, 7, 12],
        ol_splits: [1.2, 1.2, 1.2, 1.2],
        rb_depth: 4,
      },
      strength: 'right',
      coverage_stress_points: ['run_pass_hybrid', 'downhill_run_game', 'trips_overload'],
    },
    {
      formation_id: 'pistol_doubles_11_engine',
      formation_name: 'Pistol Doubles',
      personnel: '11',
      alignment: {
        left_side: ['X', 'H'],
        right_side: ['Y', 'Z'],
        backfield: ['RB'],
      },
      spacing: {
        wr_splits: [12, 5, 10, 2],
        ol_splits: [1.2, 1.2, 1.2, 1.2],
        rb_depth: 4,
      },
      strength: 'right',
      coverage_stress_points: ['rpo_friendly', 'balanced_run_pass', 'te_seam_threat'],
    },
    {
      formation_id: 'twins_te_12_engine',
      formation_name: 'Twins TE',
      personnel: '12',
      alignment: {
        left_side: ['X'],
        right_side: ['H', 'Z', 'Y'],
        backfield: ['RB'],
      },
      spacing: {
        wr_splits: [12, 5, 10, 2],
        ol_splits: [1.2, 1.2, 1.2, 1.2],
        rb_depth: 5.5,
      },
      strength: 'right',
      coverage_stress_points: ['personnel_mismatch', 'te_receiving_threat', 'strong_side_run'],
    },
  ],

  concepts: [
    // === EXISTING CONCEPTS (DO NOT MODIFY) ===
    {
      concept_id: 'four_verts',
      concept_name: 'Four Verticals',
      core_routes: [
        { player: 'x_wr', route: 'go_9', depth: 20 },
        { player: 'slot_left', route: 'seam_vertical', depth: 18 },
        { player: 'slot_right', route: 'seam_vertical', depth: 18 },
        { player: 'z_wr', route: 'go_9', depth: 20 },
      ],
      spacing: { vertical_separation: [18, 20], horizontal_separation: [10] },
      read_progression: ['safety_leverage', 'seam_void', 'backside_go', 'checkdown'],
      key_defenders: ['free_safety', 'strong_safety'],
      best_vs: ['cover_3', 'cover_1', 'man'],
      weak_vs: ['cover_2', 'cover_4'],
      qb_key: 'Read safety post-snap. Throw seam void between safeties or force 1-on-1 on outside go.',
      coaching_cue: 'Attack the seam between safeties. If Cover 2, throw outside go. If Cover 1/3, hit open seam.',
    },
    {
      concept_id: 'mesh_core',
      concept_name: 'Mesh',
      core_routes: [
        { player: 'slot_wr', route: 'shallow_cross_5', depth: 3 },
        { player: 'tight_end', route: 'shallow_cross_5', depth: 3 },
        { player: 'outside_wr', route: 'go_9', depth: 20 },
        { player: 'running_back', route: 'flat_arrow_3', depth: 3 },
      ],
      spacing: { vertical_separation: [3, 20] },
      read_progression: ['mesh_crossers', 'go_clear', 'rb_checkdown'],
      key_defenders: ['mike_linebacker', 'free_safety'],
      best_vs: ['man', 'cover_1', 'cover_3'],
      weak_vs: ['pattern_match', 'cover_4'],
      qb_key: 'Two crossers brush shoulders at 3 yards — throw to whoever gets clean release from man defender.',
      coaching_cue: 'Man coverage beater. The rub at the mesh point creates separation. First one open gets the ball.',
    },
    {
      concept_id: 'smash_core',
      concept_name: 'Smash',
      core_routes: [
        { player: 'outside_wr', route: 'hitch_5', depth: 5 },
        { player: 'slot_wr', route: 'corner_10', depth: 10 },
        { player: 'running_back', route: 'flat_arrow_3', depth: 3 },
      ],
      spacing: { vertical_separation: [5, 10] },
      read_progression: ['corner_cb_depth', 'corner_route', 'hitch_underneath', 'rb_flat'],
      key_defenders: ['cornerback'],
      best_vs: ['cover_2', 'cover_4', 'two_high'],
      weak_vs: ['cover_3', 'man'],
      qb_key: 'Hi-lo the corner. If he bails, throw hitch. If he plays hitch, throw corner over the top.',
      coaching_cue: 'Two-high beater. Hitch holds the corner down, corner goes over the top. One of them is always open.',
    },

    // === DAY 1 INSTALL ===
    {
      concept_id: 'stick_core',
      concept_name: 'Stick',
      core_routes: [
        { player: 'tight_end', route: 'stick_6', depth: 6 },
        { player: 'outside_wr', route: 'flat_arrow_3', depth: 3 },
        { player: 'backside_wr', route: 'go_9', depth: 20 },
      ],
      spacing: { vertical_separation: [3, 6, 20], triangle_concept: true },
      read_progression: ['flat_defender_read', 'stick_sit', 'flat_arrow', 'backside_go'],
      key_defenders: ['flat_defender'],
      best_vs: ['cover_3', 'cover_4', 'zone', 'man'],
      weak_vs: ['tampa_2', 'pattern_match'],
      qb_key: 'Read flat defender — if he widens to flat, throw stick. If he sits on stick, throw flat.',
      coaching_cue: 'Triangle read on the flat defender. He cannot cover both the stick and the flat. Give it to whoever he leaves open.',
    },
    {
      concept_id: 'curl_flat_core',
      concept_name: 'Curl/Flat',
      core_routes: [
        { player: 'outside_wr', route: 'curl_12', depth: 12 },
        { player: 'slot_wr', route: 'flat_arrow_3', depth: 3 },
        { player: 'backside_wr', route: 'dig_12', depth: 12 },
      ],
      spacing: { vertical_separation: [3, 12], horizontal_separation: [8] },
      read_progression: ['flat_defender_hilo', 'curl', 'flat', 'backside_dig'],
      key_defenders: ['flat_defender', 'hook_linebacker'],
      best_vs: ['cover_3', 'cover_4', 'quarters'],
      weak_vs: ['cover_2', 'man'],
      qb_key: 'Hi-lo the flat defender. If he drops, throw flat underneath. If he stays low, hit the curl over the top.',
      coaching_cue: 'Classic Cover 3 beater. The hook defender is wrong no matter what he does. Make him choose and throw opposite.',
    },
    {
      concept_id: 'flood_core',
      concept_name: 'Flood',
      core_routes: [
        { player: 'outside_wr', route: 'go_9', depth: 20 },
        { player: 'slot_wr', route: 'sail_16', depth: 16 },
        { player: 'running_back', route: 'flat_arrow_3', depth: 3 },
      ],
      spacing: { vertical_separation: [3, 16, 20] },
      read_progression: ['deep_clear', 'sail', 'flat', 'checkdown'],
      key_defenders: ['flat_defender', 'deep_third_defender'],
      best_vs: ['cover_3', 'cover_1', 'man'],
      weak_vs: ['cover_2', 'cover_4'],
      qb_key: '3-level sideline stretch. Read deep to short: if corner sits on sail, throw flat. If corner bails, throw sail.',
      coaching_cue: 'Three levels to one side. The flat defender and corner cannot cover all three. Go deepest open.',
    },
    {
      concept_id: 'drive_core',
      concept_name: 'Drive',
      core_routes: [
        { player: 'slot_wr', route: 'shallow_cross_5', depth: 3 },
        { player: 'backside_wr', route: 'dig_12', depth: 12 },
        { player: 'outside_wr', route: 'go_9', depth: 20 },
        { player: 'running_back', route: 'flat_arrow_3', depth: 3 },
      ],
      spacing: { vertical_separation: [3, 12, 20] },
      read_progression: ['shallow_cross', 'dig', 'go_clear', 'rb_checkdown'],
      key_defenders: ['mike_linebacker', 'hook_linebacker'],
      best_vs: ['cover_3', 'cover_1', 'man'],
      weak_vs: ['tampa_2', 'pattern_match'],
      qb_key: 'Read Mike LB. If he drops with dig, throw shallow underneath. If he squats on shallow, hit dig over the top.',
      coaching_cue: 'Hi-lo the linebackers. Shallow is first read — if it is covered, the dig is open behind them.',
    },

    // === DAY 2 INSTALL ===
    {
      concept_id: 'dagger_core',
      concept_name: 'Dagger',
      core_routes: [
        { player: 'slot_wr', route: 'seam_vertical', depth: 18 },
        { player: 'outside_wr', route: 'dig_12', depth: 12 },
        { player: 'backside_wr', route: 'shallow_cross_5', depth: 3 },
      ],
      spacing: { vertical_separation: [3, 12, 18] },
      read_progression: ['safety_key', 'dig', 'seam_clear', 'shallow_opposite'],
      key_defenders: ['free_safety', 'hook_linebacker'],
      best_vs: ['cover_3', 'cover_1', 'quarters'],
      weak_vs: ['cover_2', 'tampa_2'],
      qb_key: 'Read safety. Seam clears him deep — throw dig behind LBs. If LBs expand for dig, throw shallow.',
      coaching_cue: 'The seam is the clear-out. Your money throw is the dig at 12. If LBs rob it, come back to shallow.',
    },
    {
      concept_id: 'y_cross_core',
      concept_name: 'Y-Cross',
      core_routes: [
        { player: 'tight_end', route: 'dig_12', depth: 15 },
        { player: 'outside_wr', route: 'post_12', depth: 12 },
        { player: 'slot_wr', route: 'flat_arrow_3', depth: 3 },
      ],
      spacing: { vertical_separation: [3, 12, 15], horizontal_separation: [10] },
      read_progression: ['y_crosser', 'post_clear', 'flat_checkdown'],
      key_defenders: ['mike_linebacker', 'free_safety'],
      best_vs: ['cover_3', 'cover_1', 'man'],
      weak_vs: ['tampa_2', 'cover_2'],
      qb_key: 'Post clears the safety. Y crosses the field at 15 — throw him into the vacated middle.',
      coaching_cue: 'Y-Cross is a runaway route vs man. The crosser at 15 stretches the defense horizontally. Hit him in stride.',
    },
    {
      concept_id: 'snag_core',
      concept_name: 'Snag',
      core_routes: [
        { player: 'slot_wr', route: 'corner_10', depth: 10 },
        { player: 'tight_end', route: 'stick_6', depth: 6 },
        { player: 'running_back', route: 'flat_arrow_3', depth: 3 },
      ],
      spacing: { vertical_separation: [3, 6, 10], triangle_concept: true },
      read_progression: ['flat_defender_triangle', 'snag_sit', 'flat', 'corner'],
      key_defenders: ['flat_defender'],
      best_vs: ['cover_3', 'man', 'quarters'],
      weak_vs: ['cover_2', 'pattern_match'],
      qb_key: "Triangle read on flat defender. Corner over snag over flat — throw where the defender isn't.",
      coaching_cue: 'Inside triangle floods one defender with three options. Quick decision, throw to the open window.',
    },
    {
      concept_id: 'spacing_core',
      concept_name: 'Spacing',
      core_routes: [
        { player: 'outside_wr', route: 'hitch_5', depth: 5 },
        { player: 'slot_wr', route: 'stick_6', depth: 6 },
        { player: 'tight_end', route: 'stick_6', depth: 6 },
        { player: 'running_back', route: 'flat_arrow_3', depth: 3 },
      ],
      spacing: { horizontal_separation: [5, 5, 5] },
      read_progression: ['first_open_window', 'hitch', 'stick_1', 'stick_2', 'flat'],
      key_defenders: ['zone_defenders'],
      best_vs: ['zone', 'cover_3', 'cover_4', 'soft_zone'],
      weak_vs: ['man', 'press_man'],
      qb_key: 'Read zone voids. Receivers settle in windows 5 yards apart — throw to the first open one.',
      coaching_cue: 'This is a zone killer. Everyone sits at 5-6 yards, spaced 5 yards apart. Zone defenders cannot cover all the windows.',
    },
    {
      concept_id: 'levels_core',
      concept_name: 'Levels',
      core_routes: [
        { player: 'tight_end', route: 'drag_2', depth: 2 },
        { player: 'slot_wr', route: 'dig_12', depth: 12 },
        { player: 'outside_wr', route: 'post_12', depth: 15 },
      ],
      spacing: { vertical_separation: [2, 12, 15] },
      read_progression: ['mlb_depth', 'dig', 'drag', 'post_alert'],
      key_defenders: ['mike_linebacker', 'hook_linebacker'],
      best_vs: ['cover_3', 'cover_1', 'man'],
      weak_vs: ['tampa_2', 'cover_2'],
      qb_key: 'Read MLB depth. Three in-breakers at staggered depths — throw to the level he vacates.',
      coaching_cue: 'Staggered in-breakers stretch the LBs vertically. If Mike drops, throw drag. If Mike sits, throw dig.',
    },

    // === ADVANCED / SITUATIONAL ===
    {
      concept_id: 'mills_core',
      concept_name: 'Mills (Post-Dig)',
      core_routes: [
        { player: 'outside_wr', route: 'post_12', depth: 15 },
        { player: 'slot_wr', route: 'dig_12', depth: 12 },
        { player: 'running_back', route: 'flat_arrow_3', depth: 3 },
      ],
      spacing: { vertical_separation: [3, 12, 15] },
      read_progression: ['safety_hilo', 'post', 'dig', 'flat_checkdown'],
      key_defenders: ['free_safety', 'strong_safety'],
      best_vs: ['cover_4', 'quarters', 'cover_3'],
      weak_vs: ['cover_2', 'tampa_2'],
      qb_key: 'Hi-lo the safety. Post over dig on same side. If safety jumps post, throw dig underneath.',
      coaching_cue: 'Classic post-dig combo. OUTSIDE receiver runs post, INSIDE runs dig. Safety is wrong either way.',
    },
    {
      concept_id: 'spot_core',
      concept_name: 'Spot',
      core_routes: [
        { player: 'outside_wr', route: 'corner_10', depth: 10 },
        { player: 'slot_wr', route: 'stick_6', depth: 6 },
        { player: 'running_back', route: 'flat_arrow_3', depth: 3 },
      ],
      spacing: { vertical_separation: [3, 6, 10], triangle_concept: true },
      read_progression: ['flat_defender_triangle', 'spot_sit', 'flat', 'corner'],
      key_defenders: ['flat_defender'],
      best_vs: ['cover_3', 'cover_4', 'quarters'],
      weak_vs: ['man', 'press_man'],
      qb_key: 'Identical to Snag — triangle on flat defender. Spot is typically from compressed/bunch sets.',
      coaching_cue: 'Same triangle read as Snag. Three levels on one defender. Throw to the void.',
    },
    {
      concept_id: 'switch_rub_core',
      concept_name: 'Switch',
      core_routes: [
        { player: 'outside_wr', route: 'slant_5', depth: 5 },
        { player: 'slot_wr', route: 'out_8', depth: 8 },
        { player: 'backside_wr', route: 'go_9', depth: 20 },
      ],
      spacing: { horizontal_separation: [5] },
      read_progression: ['crossing_action', 'slant_inside', 'out_outside', 'go_alert'],
      key_defenders: ['cornerback', 'slot_defender'],
      best_vs: ['man', 'press_man', 'cover_1'],
      weak_vs: ['zone', 'cover_3', 'cover_4'],
      qb_key: 'Receivers cross paths to create rub vs man. Throw to whoever gets free from the pick action.',
      coaching_cue: 'Man coverage beater. The crossing paths create natural picks. Read whose defender gets hung up.',
    },
  ],

  timingRules: [
    // === EXISTING TIMING RULE (DO NOT MODIFY) ===
    {
      timing_id: 'three_step_quick',
      drop_type: 'three_step',
      drop_duration_seconds: 1.5,
      route_numbers_allowed: [0, 1, 2],
    },

    // === NEW TIMING RULES ===
    {
      timing_id: 'five_step_intermediate',
      drop_type: 'five_step',
      drop_duration_seconds: 2.2,
      route_numbers_allowed: [3, 4, 5, 6, 7],
    },
    {
      timing_id: 'seven_step_deep',
      drop_type: 'seven_step',
      drop_duration_seconds: 3.0,
      route_numbers_allowed: [3, 7, 8, 9],
    },
    {
      timing_id: 'play_action_deep',
      drop_type: 'play_action',
      drop_duration_seconds: 3.2,
      route_numbers_allowed: [3, 6, 7, 8, 9],
    },
  ],

  spacingRules: [
    // === EXISTING SPACING RULE (DO NOT MODIFY) ===
    {
      rule_id: 'vertical_stacking',
      rule_type: 'spacing_constraint',
      parameter: 'vertical_separation_yards',
      min_value: 4,
      max_value: 10,
      violation_outcome: 'defenders_cover_multiple_routes',
      correction: 'stagger_route_depths_by_minimum_4_yards',
    },

    // === NEW SPACING RULES ===
    {
      rule_id: 'horizontal_spacing_standard',
      rule_type: 'spacing_constraint',
      parameter: 'horizontal_separation_yards',
      min_value: 4,
      max_value: 8,
      violation_outcome: 'one_defender_brackets_two_routes',
      correction: 'widen_splits_or_adjust_route_stems_for_4_plus_yards_separation',
    },
    {
      rule_id: 'sideline_spacing',
      rule_type: 'spacing_constraint',
      parameter: 'horizontal_separation_yards',
      min_value: 3,
      max_value: 6,
      violation_outcome: 'sideline_becomes_extra_defender',
      correction: 'narrow_pre_snap_split_2_to_3_yards_or_convert_to_inside_breaking_route',
    },
    {
      rule_id: 'mesh_point_crossing',
      rule_type: 'spacing_constraint',
      parameter: 'vertical_separation_yards',
      min_value: 0.5,
      max_value: 1.5,
      violation_outcome: 'crossers_too_far_apart_no_rub_effect',
      correction: 'coach_receivers_to_brush_shoulders_at_mesh_point',
    },
    {
      rule_id: 'deep_route_separation',
      rule_type: 'spacing_constraint',
      parameter: 'horizontal_separation_yards',
      min_value: 8,
      max_value: 15,
      violation_outcome: 'one_safety_brackets_both_deep_routes',
      correction: 'split_deep_routes_to_opposite_thirds_of_field',
    },
  ],
};
