const rawEnv = import.meta.env as Record<string, string | undefined>;

export const env: any = {
  MODE: import.meta.env.MODE,
  DEV: import.meta.env.DEV,
  PROD: import.meta.env.PROD,
  VITE_OPENAI_API_KEY: rawEnv.VITE_OPENAI_API_KEY ?? '',
  VITE_AI_PROXY_ENDPOINT: rawEnv.VITE_AI_PROXY_ENDPOINT ?? '/api/ai',
  VITE_AI_PROXY_TOKEN: rawEnv.VITE_AI_PROXY_TOKEN ?? '',
  VITE_VAPID_PUBLIC_KEY: rawEnv.VITE_VAPID_PUBLIC_KEY ?? '',
  VITE_FIREBASE_API_KEY: rawEnv.VITE_FIREBASE_API_KEY ?? rawEnv.NEXT_PUBLIC_FIREBASE_API_KEY ?? '',
  VITE_FIREBASE_AUTH_DOMAIN: rawEnv.VITE_FIREBASE_AUTH_DOMAIN ?? rawEnv.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN ?? '',
  VITE_FIREBASE_PROJECT_ID: rawEnv.VITE_FIREBASE_PROJECT_ID ?? rawEnv.NEXT_PUBLIC_FIREBASE_PROJECT_ID ?? '',
  VITE_FIREBASE_STORAGE_BUCKET: rawEnv.VITE_FIREBASE_STORAGE_BUCKET ?? rawEnv.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET ?? '',
  VITE_FIREBASE_MESSAGING_SENDER_ID: rawEnv.VITE_FIREBASE_MESSAGING_SENDER_ID ?? rawEnv.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID ?? '',
  VITE_FIREBASE_APP_ID: rawEnv.VITE_FIREBASE_APP_ID ?? rawEnv.NEXT_PUBLIC_FIREBASE_APP_ID ?? '',
  VITE_FIREBASE_MEASUREMENT_ID: rawEnv.VITE_FIREBASE_MEASUREMENT_ID ?? rawEnv.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID ?? '',
  VITE_USE_EMULATOR: rawEnv.VITE_USE_EMULATOR ?? 'false',
  VITE_VERSION: rawEnv.VITE_VERSION ?? '1.0.0',
  VITE_BUILD_NUMBER: rawEnv.VITE_BUILD_NUMBER,
  VITE_ERROR_REPORTING_ENDPOINT: rawEnv.VITE_ERROR_REPORTING_ENDPOINT ?? '/api/errors'
} as const;
