name: 🧪 E2E Tests

# This workflow runs E2E tests on pull requests and pushes
on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    # Determine environment based on branch
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: 🔧 Determine Environment
      id: env
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "environment=prod" >> $GITHUB_OUTPUT
          echo "url=https://coach-core-ai.web.app" >> $GITHUB_OUTPUT
        elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
          echo "environment=staging" >> $GITHUB_OUTPUT
          echo "url=https://coach-core-ai-staging.web.app" >> $GITHUB_OUTPUT
        else
          echo "environment=staging" >> $GITHUB_OUTPUT
          echo "url=https://coach-core-ai-staging.web.app" >> $GITHUB_OUTPUT
        fi
      
    - name: 🔧 Setup Node.js v18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: 📦 Install dependencies
      run: npm ci
      
    - name: 🔧 Setup Cypress
      run: |
        npm install cypress --save-dev
        npx cypress verify
        
    - name: 🧪 Run E2E Tests
      run: |
        if [[ "${{ steps.env.outputs.environment }}" == "staging" ]]; then
          npm run test:e2e:staging
        else
          npm run test:e2e:production
        fi
      env:
        CYPRESS_BASE_URL: ${{ steps.env.outputs.url }}
        
    - name: 📊 Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cypress-results-${{ steps.env.outputs.environment }}
        path: |
          cypress/screenshots
          cypress/videos
          cypress/reports
        retention-days: 7
        
    - name: 📊 Test summary
      if: always()
      run: |
        echo "## 🧪 E2E Test Results" >> $GITHUB_STEP_SUMMARY
        echo "- **Environment**: ${{ steps.env.outputs.environment }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Test URL**: ${{ steps.env.outputs.url }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Test Status**: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Node.js Version**: $(node --version)" >> $GITHUB_STEP_SUMMARY
        echo "- **NPM Version**: $(npm --version)" >> $GITHUB_STEP_SUMMARY

